sudo: required
services:
    - docker

before_install:
    - docker build -t jaredbrown0/react-fib-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jaredbrown0/react-fib-test npm test

after_success:
    - docker build -t jaredbrown0/docker-fib-client ./client
    - docker build -t jaredbrown0/docker-fib-nginx ./nginx
    - docker build -t jaredbrown0/docker-fib-server ./server
    - docker build -t jaredbrown0/docker-fib-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jaredbrown0/docker-fib-client
    - docker push jaredbrown0/docker-fib-nginx
    - docker push jaredbrown0/docker-fib-server
    - docker push jaredbrown0/docker-fib-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-fib"
    env: "DockerFib-env"
    bucket_name: "elasticbeanstalk-us-east-2-984015403767"
    bucket_path: "docker-fib"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY